### ISSUE TITLE
Pre-Demo Misc To-do

### ISSUE THREAD

**Issue by SybelBlue** [SybelBlue/codesign-genie#8]
- [x] Some static back-up decks 
- [x] Gaps in the grid
- [x] Card deck changer
- [x] Differentiated `ClassLabel` styles if the class is missing
- [x] Debug mode store
